#! /bin/bash/

CELLDIM_X=20
CELLDIM_Y=20
CELLDIM_Z=20
SLICE_THICKNESS=2
PIXEL_SIZE=0.1
NUM_GPUS=4
NUM_THREADS=24
MIN_DETECTOR_ANGLE=10
MAX_DETECTOR_ANGLE=35
INPUT_FILENAME=../MATLAB/randCell.txt

for PROBE_TILT_X in {0..10..2}
  do
	for PROBE_TILT_Y in {0..10..2}
	  do
	  	./prism -i ${INPUT_FILENAME} -2D ${MIN_DETECTOR_ANGLE} ${MAX_DETECTOR_ANGLE} -3D 0 -c ${CELLDIM_X} ${CELLDIM_Y} ${CELLDIM_Z} -s ${SLICE_THICKNESS} -p ${PIXEL_SIZE} -o Xtilt_${PROBE_TILT_X}_Ytilt_${PROBE_TILT_Y}.mrc -g ${NUM_GPUS} -j ${NUM_THREADS}
	  done
  done

python combine.py
